# Generated by Selenium IDE (manually adapted)
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestSessionCookie():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_session_cookie(self):
        # Navigate to your site (HTTPS + port 443 assumed)
        self.driver.get("https://localhost/login.php")
        self.driver.set_window_size(1936, 1048)

        # After loading, get cookies from browser
        cookies = self.driver.get_cookies()

        # Extract cookie names for easier asserts
        cookie_names = [c["name"] for c in cookies]

        # Assert PHPSESSID exists → meaning PHP is managing session
        assert "PHPSESSID" in cookie_names, "PHPSESSID cookie missing!"

        # Optionally assert that there is NO raw cookie
        # Replace 'raw' with any name you want to forbid
        forbidden_cookies = ["raw", "session", "auth", "mycookie"]
        for f in forbidden_cookies:
            assert f not in cookie_names, f"Forbidden cookie {f} detected!"

        # Optional: Ensure the PHPSESSID cookie has a value
        phpsessid_value = next(
            c["value"] for c in cookies if c["name"] == "PHPSESSID"
        )
        assert phpsessid_value not in ("", None), "Empty PHPSESSID value!"
